apiVersion: apps/v1
kind: Deployment
metadata:
  name: utk-springboot
spec:
  replicas: 3
  selector:
    matchLabels:
      app: utk-springboot
  template:
    metadata:
      labels:
        app: utk-springboot
    spec:
      containers:
        - name: utk-springboot
          image: utk1311/spring-3-example-docker:latest
          ports:
            - containerPort: 8089
          env:
            - name: PORT
              value: "8089"
---
apiVersion: v1
kind: Service
metadata:
  name: utk-springboot
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8089
  selector:
    app: utk-springboot